import pandas as pd
DTYPES_CONVERT_DICT = {
    "Spend__c": float,
    "Trx__c": float,
    "Avg_Ticket__c": float,
    "Avg_Ticket_Rank__c": float,
    "Customer__c": str,
    "Product__c": str,
    "Indexed_Number_of_cards__c": float,
    "Indexed_Spend__c": float,
    "Indexed_Trx__c": float,
    "Industry__c": str,
    "Month__c": str,
    "Year__c": str,
    "Municipality__c": str,
    "Province__c": str,
    "Region__c": str,
    "Nationality__c": str,
    "Num_cards_Rank__c": float,
    "Spend_per_card__c": float,
    "Spend_per_card_Rank__c": float,
    "Spend_Rank__c": float,
    "Trx_Rank__c": float,
    "Var_MoM_Avg_Ticket__c": float,
    "Var_MoM_Num_Cards__c": float,
    "Var_MoM_Spend__c": float,
    "Var_MoM_Spend_per_Card__c": float,
    "Var_MoM_Trx__c": float,
    "Var_Yo2Y_Avg_Ticket__c": float,
    "Var_Yo2Y_Num_Cards__c": float,
    "Var_Yo2Y_Spend__c": float,
    "Var_Yo2Y_Spend_per_Card__c": float,
    "Var_Yo2Y_Trx__c": float,
    "Var_Yo3Y_Avg_Ticket__c": float,
    "Var_Yo3Y_Num_Cards__c": float,
    "Var_Yo3Y_Spend__c": float,
    "Var_Yo3Y_Spend_per_Card__c": float,
    "Var_Yo3Y_Trx__c": float,
    "Var_YoY_Avg_Ticket__c": float,
    "Var_YoY_Num_Cards__c": float,
    "Var_YoY_Spend__c": float,
    "Var_YoY_Spend_per_Card__c": float,
    "Var_YoY_Trx__c": float,
    "View__c": str,
    "Week_Start_Date__c": str,
    "Year_Month_Date__c": str,
    "Zip_Code__c": 'category'
}

def convert(df):
    df = df.astype(DTYPES_CONVERT_DICT)
    return df